apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: partivo-tickets
resources:
  - namespace.yaml
  - secrets/ghcr-credentials.sealed.yaml
  - frontend.yaml
  - console.yaml
  - consumer.yaml
  - ingress.yaml
