---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: partivo-tickets
spec:
  encryptedData:
    .dockerconfigjson: AgB8DViUY5TyAR1ZiSIh3runagL7r5z3hFCSQ+W2+cd+v8tJ+Po8oQfoVn9zQNfRoYlI6TV8MBin57qa8jpY9Kncaw8K81jPnBhn2Tw1rjxt1GI2baoZ8gtnlONhOG124VMzewt9gx+QzgBMf7ebLhg551aFhpnWBsau+Sx+9ySmFmESpPhNJrJ06KDyDXKaOo7/YEwp2LzOMq6vBKWr8J+br0EhLwt/hwWzSfs7vO0zHaHWkOlx0LWigtNayCY3SAVB6BGzz1CtcQh5Yse/uZmCbBU3p49V1hZ7D9nKhG5rs6iJALzm1wBJtU1EsYJJzJl+4K30pkyCsp9a83+jgIE0DX83/On2OEJhxwzET/y6ojMo8+QNl49cGEZpUW5oP4aXOi8k/6Cxn0Sw8oL8SgoEhA2vuYDiUO/AljVspLVYZn7bAs+2eIccVw5z4xdnTID/k255NeAtGmeT9JCS0YqcfeB6zPMMZlCgq4tn3PF0hrlin3+VZmgRdqIAtmx+o91I0w4KgxozFdIxv9nrlKt5IIltu0s6rwFBZidHDSg+TkYCBcGEG+CIs19bQOlh4xNtd5Y11KChCU9D3zi8M6klSa1sFwCyJIQP+0IGBiih4GHOD+Qb8ufkcpthHbxCv9J3cCOx94wpjhhQMTvYt8OyxiY4UmqVRZu3v1U01dyvcCdcyikcL4HtRxcySy3iTvGVD7wTPfCduoX/swcVpuXBhbLPiicFKKWOB17LdWjiBVmtIgw5ZpkchDV5cRq5L0GnU9bEaly4xzLCveY5TvRMfHBHiE5VHJH1tbqZIjxNd8Dse+x1+w5srxYA69LpKmmCXcrta/njjU4ee9aHR2eUyM8VDCy5ReqcBGyStxCu4cQrABi2sL/WwKVOpeklZP5YziLr7KXYvKE6fQJPGiIb/C5FhFvJMrUbn72iFi3aDNL9QIdbHrQ8how95AwX24KciqMacMSiU917J6e/0+GMAsC5f011PQ==
  template:
    metadata:
      name: ghcr-credentials
      namespace: partivo-tickets
    type: kubernetes.io/dockerconfigjson
